lines = [
    'import { useState, useEffect } from "react";\n',
    '\n',
    'const API = "https://autosell-production-b292.up.railway.app";\n',
    '\n',
    'export default function OrdersPage() {\n',
    '  const [orders, setOrders] = useState([]);\n',
    '  const [loading, setLoading] = useState(true);\n',
    '  const [search, setSearch] = useState("");\n',
    '\n',
    '  useEffect(() => {\n',
    '    fetch(`${API}/orders/`)\n',
    '      .then(res => res.json())\n',
    '      .then(data => { setOrders(data); setLoading(false); })\n',
    '      .catch(() => setLoading(false));\n',
    '  }, []);\n',
    '\n',
    '  const filtered = orders.filter(o =>\n',
    '    o.order_id?.toLowerCase().includes(search.toLowerCase()) ||\n',
    '    o.customer_name?.toLowerCase().includes(search.toLowerCase())\n',
    '  );\n',
    '\n',
    '  return (\n',
    '    <div style={{ minHeight: "100vh", background: "#030712", color: "white", padding: "24px" }}>\n',
    '      <h1 style={{ fontSize: "24px", fontWeight: "bold", marginBottom: "4px" }}>Orders</h1>\n',
    '      <p style={{ color: "#6b7280", marginBottom: "24px" }}>Real database se orders</p>\n',
    '\n',
    '      <input\n',
    '        placeholder="Search orders..."\n',
    '        value={search}\n',
    '        onChange={e => setSearch(e.target.value)}\n',
    '        style={{ width: "100%", background: "#111827", border: "1px solid #374151", borderRadius: "8px", padding: "10px 16px", color: "white", marginBottom: "20px", boxSizing: "border-box" }}\n',
    '      />\n',
    '\n',
    '      <div style={{ background: "#111827", borderRadius: "12px", overflow: "hidden" }}>\n',
    '        {loading ? (\n',
    '          <p style={{ textAlign: "center", padding: "40px", color: "#6b7280" }}>Loading...</p>\n',
    '        ) : filtered.length === 0 ? (\n',
    '          <p style={{ textAlign: "center", padding: "40px", color: "#6b7280" }}>Koi order nahi - Meesho CSV import karo!</p>\n',
    '        ) : (\n',
    '          <table style={{ width: "100%", borderCollapse: "collapse" }}>\n',
    '            <thead>\n',
    '              <tr style={{ borderBottom: "1px solid #1f2937" }}>\n',
    '                {["Order ID","Product","Customer","Platform","Price","Status"].map(h => (\n',
    '                  <th key={h} style={{ padding: "12px 16px", textAlign: "left", color: "#6b7280", fontSize: "12px" }}>{h}</th>\n',
    '                ))}\n',
    '              </tr>\n',
    '            </thead>\n',
    '            <tbody>\n',
    '              {filtered.map((o, i) => (\n',
    '                <tr key={i} style={{ borderBottom: "1px solid #1f2937" }}>\n',
    '                  <td style={{ padding: "12px 16px", color: "#a78bfa" }}>{o.order_id}</td>\n',
    '                  <td style={{ padding: "12px 16px" }}>{o.product_name}</td>\n',
    '                  <td style={{ padding: "12px 16px", color: "#9ca3af" }}>{o.customer_name}</td>\n',
    '                  <td style={{ padding: "12px 16px", color: "#60a5fa" }}>{o.platform}</td>\n',
    '                  <td style={{ padding: "12px 16px", color: "#4ade80" }}>Rs {o.price}</td>\n',
    '                  <td style={{ padding: "12px 16px" }}>\n',
    '                    <span style={{ background: "#1f2937", padding: "4px 10px", borderRadius: "999px", fontSize: "12px" }}>\n',
    '                      {o.status}\n',
    '                    </span>\n',
    '                  </td>\n',
    '                </tr>\n',
    '              ))}\n',
    '            </tbody>\n',
    '          </table>\n',
    '        )}\n',
    '      </div>\n',
    '    </div>\n',
    '  );\n',
    '}\n',
]

with open("src/pages/OrdersPage.jsx", "w", encoding="utf-8") as f:
    f.writelines(lines)

print("OrdersPage written!")