lines = [
    'import { useState } from "react";\n',
    '\n',
    'export default function AICustomerServicePage() {\n',
    '  const [messages, setMessages] = useState([\n',
    '    { role: "assistant", content: "Namaste! Main AutoSell ka AI assistant hoon. Meesho, Flipkart, pricing, ya orders ke baare mein kuch bhi poocho!" }\n',
    '  ]);\n',
    '  const [input, setInput] = useState("");\n',
    '  const [loading, setLoading] = useState(false);\n',
    '\n',
    '  const sendMessage = async () => {\n',
    '    if (!input.trim()) return;\n',
    '    const userMsg = { role: "user", content: input };\n',
    '    const newMessages = [...messages, userMsg];\n',
    '    setMessages(newMessages);\n',
    '    setInput("");\n',
    '    setLoading(true);\n',
    '\n',
    '    try {\n',
    '      const response = await fetch("https://api.anthropic.com/v1/messages", {\n',
    '        method: "POST",\n',
    '        headers: { "Content-Type": "application/json" },\n',
    '        body: JSON.stringify({\n',
    '          model: "claude-sonnet-4-20250514",\n',
    '          max_tokens: 1000,\n',
    '          system: "You are AutoSell AI assistant for Indian dropshippers. Help with Meesho, Flipkart, Amazon India, product pricing, order management, and dropshipping advice. Respond in Hinglish (Hindi-English mix). Be concise and practical.",\n',
    '          messages: newMessages\n',
    '        })\n',
    '      });\n',
    '      const data = await response.json();\n',
    '      const reply = data.content[0].text;\n',
    '      setMessages([...newMessages, { role: "assistant", content: reply }]);\n',
    '    } catch (err) {\n',
    '      setMessages([...newMessages, { role: "assistant", content: "Sorry, kuch error hua. Dobara try karo." }]);\n',
    '    }\n',
    '    setLoading(false);\n',
    '  };\n',
    '\n',
    '  return (\n',
    '    <div style={{ minHeight: "100vh", background: "#030712", color: "white", display: "flex", flexDirection: "column" }}>\n',
    '      <div style={{ padding: "20px 24px", borderBottom: "1px solid #1f2937" }}>\n',
    '        <h1 style={{ fontSize: "22px", fontWeight: "bold", margin: 0 }}>AI Support</h1>\n',
    '        <p style={{ color: "#6b7280", margin: "4px 0 0", fontSize: "13px" }}>Powered by Claude AI</p>\n',
    '      </div>\n',
    '\n',
    '      <div style={{ flex: 1, overflowY: "auto", padding: "20px 24px", display: "flex", flexDirection: "column", gap: "12px" }}>\n',
    '        {messages.map((msg, i) => (\n',
    '          <div key={i} style={{ display: "flex", justifyContent: msg.role === "user" ? "flex-end" : "flex-start" }}>\n',
    '            <div style={{\n',
    '              maxWidth: "75%", padding: "12px 16px", borderRadius: "16px", fontSize: "14px", lineHeight: "1.5",\n',
    '              background: msg.role === "user" ? "#7c3aed" : "#111827",\n',
    '              color: "white"\n',
    '            }}>\n',
    '              {msg.content}\n',
    '            </div>\n',
    '          </div>\n',
    '        ))}\n',
    '        {loading && (\n',
    '          <div style={{ display: "flex", justifyContent: "flex-start" }}>\n',
    '            <div style={{ background: "#111827", padding: "12px 16px", borderRadius: "16px", fontSize: "14px", color: "#6b7280" }}>\n',
    '              Soch raha hoon...\n',
    '            </div>\n',
    '          </div>\n',
    '        )}\n',
    '      </div>\n',
    '\n',
    '      <div style={{ padding: "16px 24px", borderTop: "1px solid #1f2937", display: "flex", gap: "12px" }}>\n',
    '        <input\n',
    '          value={input}\n',
    '          onChange={e => setInput(e.target.value)}\n',
    '          onKeyDown={e => e.key === "Enter" && sendMessage()}\n',
    '          placeholder="Kuch bhi poocho..."\n',
    '          style={{ flex: 1, background: "#111827", border: "1px solid #374151", borderRadius: "12px", padding: "12px 16px", color: "white", fontSize: "14px", outline: "none" }}\n',
    '        />\n',
    '        <button\n',
    '          onClick={sendMessage}\n',
    '          disabled={loading}\n',
    '          style={{ background: "#7c3aed", color: "white", border: "none", borderRadius: "12px", padding: "12px 20px", fontSize: "14px", fontWeight: "600", cursor: "pointer" }}>\n',
    '          Send\n',
    '        </button>\n',
    '      </div>\n',
    '    </div>\n',
    '  );\n',
    '}\n',
]

with open("src/pages/AICustomerServicePage.jsx", "w", encoding="utf-8") as f:
    f.writelines(lines)

print("AI Support page written!")