lines = [
    'import { useState, useEffect } from "react";\n',
    '\n',
    'const API = "https://autosell-production-b292.up.railway.app";\n',
    '\n',
    'export default function SettingsPage() {\n',
    '  const [settings, setSettings] = useState({\n',
    '    store_name: "", phone: "", meesho_api_key: "", flipkart_api_key: "",\n',
    '    auto_pricing: false, notification_email: true\n',
    '  });\n',
    '  const [saved, setSaved] = useState(false);\n',
    '  const [loading, setLoading] = useState(true);\n',
    '\n',
    '  useEffect(() => {\n',
    '    fetch(`${API}/settings/`)\n',
    '      .then(res => res.json())\n',
    '      .then(data => { setSettings(data); setLoading(false); })\n',
    '      .catch(() => setLoading(false));\n',
    '  }, []);\n',
    '\n',
    '  const handleSave = async () => {\n',
    '    await fetch(`${API}/settings/`, {\n',
    '      method: "PUT",\n',
    '      headers: { "Content-Type": "application/json" },\n',
    '      body: JSON.stringify(settings)\n',
    '    });\n',
    '    setSaved(true);\n',
    '    setTimeout(() => setSaved(false), 2000);\n',
    '  };\n',
    '\n',
    '  const inputStyle = {\n',
    '    width: "100%", background: "#1f2937", border: "1px solid #374151",\n',
    '    borderRadius: "8px", padding: "10px 14px", color: "white",\n',
    '    marginTop: "6px", boxSizing: "border-box", fontSize: "14px"\n',
    '  };\n',
    '\n',
    '  if (loading) return <div style={{ background: "#030712", minHeight: "100vh", color: "white", padding: "24px" }}>Loading...</div>;\n',
    '\n',
    '  return (\n',
    '    <div style={{ minHeight: "100vh", background: "#030712", color: "white", padding: "24px" }}>\n',
    '      <h1 style={{ fontSize: "24px", fontWeight: "bold", marginBottom: "4px" }}>Settings</h1>\n',
    '      <p style={{ color: "#6b7280", marginBottom: "24px" }}>Store aur platform settings</p>\n',
    '\n',
    '      <div style={{ background: "#111827", borderRadius: "12px", padding: "20px", marginBottom: "16px" }}>\n',
    '        <h2 style={{ color: "#a78bfa", marginBottom: "16px" }}>Store Info</h2>\n',
    '        <div style={{ marginBottom: "12px" }}>\n',
    '          <label style={{ color: "#9ca3af", fontSize: "13px" }}>Store Name</label>\n',
    '          <input style={inputStyle} value={settings.store_name || ""}\n',
    '            onChange={e => setSettings({...settings, store_name: e.target.value})} />\n',
    '        </div>\n',
    '        <div>\n',
    '          <label style={{ color: "#9ca3af", fontSize: "13px" }}>Phone</label>\n',
    '          <input style={inputStyle} value={settings.phone || ""}\n',
    '            onChange={e => setSettings({...settings, phone: e.target.value})} />\n',
    '        </div>\n',
    '      </div>\n',
    '\n',
    '      <div style={{ background: "#111827", borderRadius: "12px", padding: "20px", marginBottom: "16px" }}>\n',
    '        <h2 style={{ color: "#60a5fa", marginBottom: "16px" }}>Platform API Keys</h2>\n',
    '        <div style={{ marginBottom: "12px" }}>\n',
    '          <label style={{ color: "#9ca3af", fontSize: "13px" }}>Meesho Supplier Key</label>\n',
    '          <input type="password" style={inputStyle} value={settings.meesho_api_key || ""}\n',
    '            placeholder="Enter Meesho API key"\n',
    '            onChange={e => setSettings({...settings, meesho_api_key: e.target.value})} />\n',
    '        </div>\n',
    '        <div>\n',
    '          <label style={{ color: "#9ca3af", fontSize: "13px" }}>Flipkart Seller Key</label>\n',
    '          <input type="password" style={inputStyle} value={settings.flipkart_api_key || ""}\n',
    '            placeholder="Enter Flipkart API key"\n',
    '            onChange={e => setSettings({...settings, flipkart_api_key: e.target.value})} />\n',
    '        </div>\n',
    '      </div>\n',
    '\n',
    '      <div style={{ background: "#111827", borderRadius: "12px", padding: "20px", marginBottom: "24px" }}>\n',
    '        <h2 style={{ color: "#4ade80", marginBottom: "16px" }}>Preferences</h2>\n',
    '        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "12px" }}>\n',
    '          <span style={{ color: "#d1d5db" }}>Auto Pricing</span>\n',
    '          <input type="checkbox" checked={settings.auto_pricing || false}\n',
    '            onChange={e => setSettings({...settings, auto_pricing: e.target.checked})} />\n',
    '        </div>\n',
    '        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>\n',
    '          <span style={{ color: "#d1d5db" }}>Email Notifications</span>\n',
    '          <input type="checkbox" checked={settings.notification_email || false}\n',
    '            onChange={e => setSettings({...settings, notification_email: e.target.checked})} />\n',
    '        </div>\n',
    '      </div>\n',
    '\n',
    '      <button onClick={handleSave}\n',
    '        style={{ width: "100%", background: saved ? "#16a34a" : "#7c3aed", color: "white",\n',
    '          padding: "14px", borderRadius: "12px", border: "none", fontSize: "16px",\n',
    '          fontWeight: "600", cursor: "pointer" }}>\n',
    '        {saved ? "Saved!" : "Save Settings"}\n',
    '      </button>\n',
    '    </div>\n',
    '  );\n',
    '}\n',
]

with open("src/pages/SettingsPage.jsx", "w", encoding="utf-8") as f:
    f.writelines(lines)

print("SettingsPage written!")